<a href="https://colab.research.google.com/github/rupeshryan/DS-by-Srinivas/blob/main/Python_Pandas_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## ***Python Pandas Practice***

In [ ]:
  import pandas as pd

In [ ]:
df= pd.read_csv("/content/Salaries.csv")

In [ ]:
df.head()

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

In [ ]:
df.head(10) #first n rows

        rank discipline  phd  service   sex  salary
0       Prof          B   56       49  Male  186960
1       Prof          A   12        6  Male   93000
2       Prof          A   23       20  Male  110515
3       Prof          A   40       31  Male  131205
4       Prof          B   20       18  Male  104800
5       Prof          A   20       20  Male  122400
6  AssocProf          A   20       17  Male   81285
7       Prof          A   18       18  Male  126300
8       Prof          A   29       19  Male   94350
9       Prof          A   51       51  Male   57800

Attributes of Python

In [ ]:
df.dtypes

rank          object
discipline    object
phd            int64
service        int64
sex           object
salary         int64
dtype: object

In [ ]:
df.size

468

In [ ]:
df.shape

(78, 6)

In [ ]:
df.columns

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

In [ ]:
df.axes

[RangeIndex(start=0, stop=78, step=1),
 Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')]

In [ ]:
df.values

array([['Prof', 'B', 56, 49, 'Male', 186960],
       ['Prof', 'A', 12, 6, 'Male', 93000],
       ['Prof', 'A', 23, 20, 'Male', 110515],
       ['Prof', 'A', 40, 31, 'Male', 131205],
       ['Prof', 'B', 20, 18, 'Male', 104800],
       ['Prof', 'A', 20, 20, 'Male', 122400],
       ['AssocProf', 'A', 20, 17, 'Male', 81285],
       ['Prof', 'A', 18, 18, 'Male', 126300],
       ['Prof', 'A', 29, 19, 'Male', 94350],
       ['Prof', 'A', 51, 51, 'Male', 57800],
       ['Prof', 'B', 39, 33, 'Male', 128250],
       ['Prof', 'B', 23, 23, 'Male', 134778],
       ['AsstProf', 'B', 1, 0, 'Male', 88000],
       ['Prof', 'B', 35, 33, 'Male', 162200],
       ['Prof', 'B', 25, 19, 'Male', 153750],
       ['Prof', 'B', 17, 3, 'Male', 150480],
       ['AsstProf', 'B', 8, 3, 'Male', 75044],
       ['AsstProf', 'B', 4, 0, 'Male', 92000],
       ['Prof', 'A', 19, 7, 'Male', 107300],
       ['Prof', 'A', 29, 27, 'Male', 150500],
       ['AsstProf', 'B', 4, 4, 'Male', 92000],
       ['Prof', 'A', 33, 30, 'Male', 103106],
       ['AsstProf', 'A', 4, 2, 'Male', 73000],
       ['AsstProf', 'A', 2, 0, 'Male', 85000],
       ['Prof', 'A', 30, 23, 'Male', 91100],
       ['Prof', 'B', 35, 31, 'Male', 99418],
       ['Prof', 'A', 38, 19, 'Male', 148750],
       ['Prof', 'A', 45, 43, 'Male', 155865],
       ['AsstProf', 'B', 7, 2, 'Male', 91300],
       ['Prof', 'B', 21, 20, 'Male', 123683],
       ['AssocProf', 'B', 9, 7, 'Male', 107008],
       ['Prof', 'B', 22, 21, 'Male', 155750],
       ['Prof', 'A', 27, 19, 'Male', 103275],
       ['Prof', 'B', 18, 18, 'Male', 120000],
       ['AssocProf', 'B', 12, 8, 'Male', 119800],
       ['Prof', 'B', 28, 23, 'Male', 126933],
       ['Prof', 'B', 45, 45, 'Male', 146856],
       ['Prof', 'A', 20, 8, 'Male', 102000],
       ['AsstProf', 'B', 4, 3, 'Male', 91000],
       ['Prof', 'B', 18, 18, 'Female', 129000],
       ['Prof', 'A', 39, 36, 'Female', 137000],
       ['AssocProf', 'A', 13, 8, 'Female', 74830],
       ['AsstProf', 'B', 4, 2, 'Female', 80225],
       ['AsstProf', 'B', 5, 0, 'Female', 77000],
       ['Prof', 'B', 23, 19, 'Female', 151768],
       ['Prof', 'B', 25, 25, 'Female', 140096],
       ['AsstProf', 'B', 11, 3, 'Female', 74692],
       ['AssocProf', 'B', 11, 11, 'Female', 103613],
       ['Prof', 'B', 17, 17, 'Female', 111512],
       ['Prof', 'B', 17, 18, 'Female', 122960],
       ['AsstProf', 'B', 10, 5, 'Female', 97032],
       ['Prof', 'B', 20, 14, 'Female', 127512],
       ['Prof', 'A', 12, 0, 'Female', 105000],
       ['AsstProf', 'A', 5, 3, 'Female', 73500],
       ['AssocProf', 'A', 25, 22, 'Female', 62884],
       ['AsstProf', 'A', 2, 0, 'Female', 72500],
       ['AssocProf', 'A', 10, 8, 'Female', 77500],
       ['AsstProf', 'A', 3, 1, 'Female', 72500],
       ['Prof', 'B', 36, 26, 'Female', 144651],
       ['AssocProf', 'B', 12, 10, 'Female', 103994],
       ['AsstProf', 'B', 3, 3, 'Female', 92000],
       ['AssocProf', 'B', 13, 10, 'Female', 103750],
       ['AssocProf', 'B', 14, 7, 'Female', 109650],
       ['Prof', 'A', 29, 27, 'Female', 91000],
       ['AssocProf', 'A', 26, 24, 'Female', 73300],
       ['Prof', 'A', 36, 19, 'Female', 117555],
       ['AsstProf', 'A', 7, 6, 'Female', 63100],
       ['Prof', 'A', 17, 11, 'Female', 90450],
       ['AsstProf', 'A', 4, 2, 'Female', 77500],
       ['Prof', 'A', 28, 7, 'Female', 116450],
       ['AsstProf', 'A', 8, 3, 'Female', 78500],
       ['AssocProf', 'B', 12, 9, 'Female', 71065],
       ['Prof', 'B', 24, 15, 'Female', 161101],
       ['Prof', 'B', 18, 10, 'Female', 105450],
       ['AssocProf', 'B', 19, 6, 'Female', 104542],
       ['Prof', 'B', 17, 17, 'Female', 124312],
       ['Prof', 'A', 28, 14, 'Female', 109954],
       ['Prof', 'A', 23, 15, 'Female', 109646]], dtype=object)

In [ ]:
df.ndim

2

In [ ]:
df.shape[0]  #no of rows

78

In [ ]:
df.shape[1]   #no of columns

6

Methods of Python

In [ ]:
df.head(1)

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960

In [ ]:
df.describe()

             phd    service         salary
count  78.000000  78.000000      78.000000
mean   19.705128  15.051282  108023.782051
std    12.498425  12.139768   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.250000   5.250000   88612.500000
50%    18.500000  14.500000  104671.000000
75%    27.750000  20.750000  126774.750000
max    56.000000  51.000000  186960.000000

In [ ]:
df.max()

rank            Prof
discipline         B
phd               56
service           51
sex             Male
salary        186960
dtype: object

In [ ]:
df.std()

<ipython-input-27-ce97bb7eaef8>:1: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.std()

phd           12.498425
service       12.139768
salary     28293.661022
dtype: float64

In [ ]:
df1 = df.head(50) #mean of first 50 rows

In [ ]:
df1.mean()

<ipython-input-46-00fb6bfec183>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df1.mean()

phd            21.52
service        17.60
salary     113789.14
dtype: float64

In [ ]:
df.head(50).mean()   #chaining operation- appliying 2 methods in 1 operation

<ipython-input-47-56442511a41d>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.head(50).mean()

phd            21.52
service        17.60
salary     113789.14
dtype: float64

In [ ]:
df.phd

0     56
1     12
2     23
3     40
4     20
      ..
73    18
74    19
75    17
76    28
77    23
Name: phd, Length: 78, dtype: int64

In [ ]:
df['phd']

0     56
1     12
2     23
3     40
4     20
      ..
73    18
74    19
75    17
76    28
77    23
Name: phd, Length: 78, dtype: int64

In [ ]:
df[['phd']]

    phd
0    56
1    12
2    23
3    40
4    20
..  ...
73   18
74   19
75   17
76   28
77   23

[78 rows x 1 columns]

In [ ]:
df['phd'].describe()

count    78.000000
mean     19.705128
std      12.498425
min       1.000000
25%      10.250000
50%      18.500000
75%      27.750000
max      56.000000
Name: phd, dtype: float64

In [ ]:
df['phd'].count()

78

In [ ]:
df.phd.mean()

19.705128205128204

In [ ]:
df2=df.groupby(['rank'])   #calculating satistics based by catergory or column- for that we use groupby method

In [ ]:
df2.mean()

<ipython-input-69-4a56ca50fe8e>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df2.mean()

                 phd    service         salary
rank
AssocProf  15.076923  11.307692   91786.230769
AsstProf    5.052632   2.210526   81362.789474
Prof       27.065217  21.413043  123624.804348

In [ ]:
df.groupby(['rank']).mean()

<ipython-input-71-59c8c915524f>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby(['rank']).mean()

                 phd    service         salary
rank
AssocProf  15.076923  11.307692   91786.230769
AsstProf    5.052632   2.210526   81362.789474
Prof       27.065217  21.413043  123624.804348

In [ ]:
df.groupby('rank')['salary'].mean()

rank
AssocProf     91786.230769
AsstProf      81362.789474
Prof         123624.804348
Name: salary, dtype: float64

In [ ]:
df[df.salary > 120000] ## or df[df['salary']>120000]  ###printing all rows whose salary is > 120000 ### this is filtering

    rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
3   Prof          A   40       31    Male  131205
5   Prof          A   20       20    Male  122400
7   Prof          A   18       18    Male  126300
10  Prof          B   39       33    Male  128250
11  Prof          B   23       23    Male  134778
13  Prof          B   35       33    Male  162200
14  Prof          B   25       19    Male  153750
15  Prof          B   17        3    Male  150480
19  Prof          A   29       27    Male  150500
26  Prof          A   38       19    Male  148750
27  Prof          A   45       43    Male  155865
29  Prof          B   21       20    Male  123683
31  Prof          B   22       21    Male  155750
35  Prof          B   28       23    Male  126933
36  Prof          B   45       45    Male  146856
39  Prof          B   18       18  Female  129000
40  Prof          A   39       36  Female  137000
44  Prof          B   23       19  Female  151768
45  Prof          B   25       25  Female  140096
49  Prof          B   17       18  Female  122960
51  Prof          B   20       14  Female  127512
58  Prof          B   36       26  Female  144651
72  Prof          B   24       15  Female  161101
75  Prof          B   17       17  Female  124312

In [ ]:
df[df.sex == 'Female'].head() #selecting top 5 rows of female rows

         rank discipline  phd  service     sex  salary
39       Prof          B   18       18  Female  129000
40       Prof          A   39       36  Female  137000
41  AssocProf          A   13        8  Female   74830
42   AsstProf          B    4        2  Female   80225
43   AsstProf          B    5        0  Female   77000

In [ ]:
df[['salary','sex']]     #if we need select more thank one column then we have to use double bracket

    salary     sex
0   186960    Male
1    93000    Male
2   110515    Male
3   131205    Male
4   104800    Male
..     ...     ...
73  105450  Female
74  104542  Female
75  124312  Female
76  109954  Female
77  109646  Female

[78 rows x 2 columns]

In [ ]:
df.iloc[0]     #iloc method to fetch the requried data from the dataset

rank            Prof
discipline         B
phd               56
service           49
sex             Male
salary        186960
Name: 0, dtype: object

In [ ]:
df.iloc[:,0]    #to fetch first coloumn

0          Prof
1          Prof
2          Prof
3          Prof
4          Prof
        ...
73         Prof
74    AssocProf
75         Prof
76         Prof
77         Prof
Name: rank, Length: 78, dtype: object

In [ ]:
df.iloc[0:10,0:3]   #to fectch first 10 rows and first 3 columns

        rank discipline  phd
0       Prof          B   56
1       Prof          A   12
2       Prof          A   23
3       Prof          A   40
4       Prof          B   20
5       Prof          A   20
6  AssocProf          A   20
7       Prof          A   18
8       Prof          A   29
9       Prof          A   51

In [ ]:
df.iloc[:,4:6]      #5th and 6th coloumn

       sex  salary
0     Male  186960
1     Male   93000
2     Male  110515
3     Male  131205
4     Male  104800
..     ...     ...
73  Female  105450
74  Female  104542
75  Female  124312
76  Female  109954
77  Female  109646

[78 rows x 2 columns]

In [ ]:
  df.iloc[[59]]    #60th row

         rank discipline  phd  service     sex  salary
59  AssocProf          B   12       10  Female  103994

In [ ]:
df.iloc[[0,2]]     #1st an 3rd row

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
2  Prof          A   23       20  Male  110515

In [ ]:
df[['phd','salary']].agg(['min','mean','max'])   #Aggregate functions- to cal inidividual values of summary instead of whole

            phd         salary
min    1.000000   57800.000000
mean  19.705128  108023.782051
max   56.000000  186960.000000